const unitData = {
    "Artificial": { rarity: 1, count: 0 },
    "Human": { rarity: 1, count: 0 },
    "Exotic": { rarity: 1, count: 0 },
    "Darkener": { rarity: 1, count: 0 },
    "Techno": { rarity: 1, count: 0 },
    "Mystic": { rarity: 1, count: 0 },
    "Goner": { rarity: 1, count: 0 },
    "Class 1": { rarity: 2, count: 0 },
    "Class 2": { rarity: 2, count: 0 },
    "Class 3": { rarity: 2, count: 0 },
    "Class 4": { rarity: 2, count: 0 },
    "Class 5": { rarity: 2, count: 0 },
    "Class 6": { rarity: 2, count: 0 },
    "Class 7": { rarity: 2, count: 0 },
    "Class 8": { rarity: 2, count: 0 },
    "Class 9": { rarity: 2, count: 0 },
    "Class 10": { rarity: 2, count: 0 },
    "E (Generic)": { rarity: 2, count: 0 },
    "M (Generic)": { rarity: 2, count: 0 },
    "I (Generic)": { rarity: 2, count: 0 },
    "H (Generic)": { rarity: 2, count: 0 },
    "R (Generic)": { rarity: 2, count: 0 },
    "HeX (Generic)": { rarity: 2, count: 0 },
    "DeX (Generic)": { rarity: 2, count: 0 },
    "IeX (Generic)": { rarity: 2, count: 0 },
    "A (Generic)": { rarity: 2, count: 0 },
    "Imagination (Generic)": { rarity: 2, count: 0 },
    "Timelinear": { rarity: 2, count: 0 },
    "Experiment": { rarity: 2, count: 0 },
    "Classical": { rarity: 3, count: 0 },
    "Hypno": { rarity: 3, count: 0 },
    "Chaos": { rarity: 3, count: 0 },
    "Order": { rarity: 3, count: 0 },
    "3 (Scientist)": { rarity: 3, count: 0 },
    "Rebellion (Generic)": { rarity: 3, count: 0 },
    "4 (Archer)": { rarity: 3, count: 0 },
    "5 (Band)": { rarity: 3, count: 0 },
    "6 (Band)": { rarity: 3, count: 0 },
    "7 (Band)": { rarity: 3, count: 0 },
    "8 (Eternity)": { rarity: 3, count: 0 },
    "9 (Eternity)": { rarity: 3, count: 0 },
    "10 (Eternity)": { rarity: 3, count: 0 },
    "E (Eternity)": { rarity: 3, count: 0 },
    "M (Hypno)": { rarity: 3, count: 0 },
    "I (Scientist)": { rarity: 3, count: 0 },
    "H (Mystic)": { rarity: 3, count: 0 },
    "Real": { rarity: 3, count: 0 },
    "HeX (Soldier)": { rarity: 3, count: 0 },
    "DeX (Soldier)": { rarity: 3, count: 0 },
    "Doll Maker": { rarity: 3, count: 0 },
    "Amalgam": { rarity: 3, count: 0 },
    "The General": { rarity: 3, count: 0 },
    "Dark": { rarity: 3, count: 0 },
    "Servant": { rarity: 3, count: 0 },
    "Daisy": { rarity: 3, count: 0 },
    "Revolutionary (3rd)": { rarity: 3, count: 0 },
    "Masks": { rarity: 3, count: 0 },
    "Jester": { rarity: 3, count: 0 },
    "Sunshine": { rarity: 3, count: 0 },
    "Shadow King": { rarity: 3, count: 0 },
    "Star Dream": { rarity: 3, count: 0 },
    "Mannequin": { rarity: 3, count: 0 },
    "Electric": { rarity: 3, count: 0 },
    "Detective": { rarity: 3, count: 0 },
    "Jack Spades": { rarity: 4, count: 0 },
    "Dark (Matryoshka)": { rarity: 4, count: 0 },
    "Void": { rarity: 4, count: 0 },
    "Entropy": { rarity: 4, count: 0 },
    "Template": { rarity: 4, count: 0 },
    "Idol": { rarity: 4, count: 0 },
    "Revolutionary (Collective)": { rarity: 4, count: 0 },
    "Classical (Joy)": { rarity: 4, count: 0 },
    "Gardener": { rarity: 4, count: 0 },
    "Past": { rarity: 4, count: 0 },
    "Present": { rarity: 4, count: 0 },
    "Future": { rarity: 4, count: 0 },
    "Narcissus": { rarity: 4, count: 0 },
    "Servant (Gluttony)": { rarity: 4, count: 0 },
    "Sunshine (Decadent)": { rarity: 4, count: 0 },
    "Puppeteer": { rarity: 4, count: 0 },
    "Steampunk": { rarity: 4, count: 0 },
    "Death": { rarity: 4, count: 0 },
    "Doctor": { rarity: 4, count: 0 },
    "Chimera": { rarity: 4, count: 0 },
    "Creator (Generic)": { rarity: 5, count: 0 },
    "Dark (Space)": { rarity: 5, count: 0 },
    "Fate": { rarity: 5, count: 0 },
    "R. Random": { rarity: 5, count: 0 },
    "Green Knight": { rarity: 5, count: 0 },
};

export default unitData;